### ISSUE TITLE
Installing on Windows as a service

### ISSUE THREAD

**Issue by janaka** [vrtadmin/clamav-devel#10]
Hi,
Any support for installing Clamd as a windows service on Windows 2012 coming soon?

**Comment by ROCKNROLLKID** [comment]
I know this is an old issue, but a few years ago, a user posted how you can run ClamWin as a service. You can read the topic here: http://forums.clamwin.com/viewtopic.php?t=4178

I also found this old article on the web on how to run the native ClamAV windows port as a service, too. You can read it here: http://www.andornot.com/blog/post/How-to-set-up-ClamAV-as-a-Windows-Service-to-scan-file-streams-on-demand.aspx

I would like to know why ClamAV isn't like this already. I know it is mainly meant for Linux systems, but their are also Windows mail servers that run ClamAV, too, and running ClamAV as a service will help out a lot.

**Comment by vrtadmin** [comment]
Our official bug tracker is at https://bugzilla.clamav.net

Please file your bug there.

For any discussions on the issue, please see the ClamAV-Users or ClamAV-Devel mailing lists here:

http://www.clamav.net/contact#ml
