### ISSUE TITLE
Move ClamAV repos to the ClamAV organisation

### ISSUE THREAD

**Issue by Bengt** [vrtadmin/clamav-devel#11]
The repositories `vrtadmin/clamav-devel`, `vrtadmin/clamav-faq` and `vrtadmin/clamav-bytecode-compiler` should be moved to the `clamav` organisation to make it obvious that one has found the official repository. To do this, make sure that you own the [clamav organisation](https://github.com/clamav) and go to <https://github.com/vrtadmin/clamav-devel/settings>, click "Transfer" and follow the instructions.

**Comment by websafe** [comment]
:+1:

**Comment by vrtadmin** [comment]
I will work this issue.
-- Joel
