### ISSUE TITLE
0.98.5 is not upgrading to 0.98.6

### ISSUE THREAD

**Issue by uGiFarukh** [vrtadmin/clamav-devel#16]
Hello,

I have a CentOS VPS Server. I have install EPEL : http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm

And then installed clamav. But when I do a freshclam it always says that my version is 0.98.5 which is OUTDATED and latest version is 0.98.6

But it is not upgrading itself to the latest one...

Please solve this issue.
Thanks in advance.....

**Comment by darkex** [comment]
I think you have to install 'clamav-update' also not just 'clamav'.Like this 'yum install clamav clamav-update'.

**Comment by uGiFarukh** [comment]
After an OS re-install the problem got solved actually...

**Comment by uGiFarukh** [comment]
Again this issue comes with v0.99 of clamav. In a fresh CentOS install I have enabled Epel Repo. Then I installed Clamav using : yum install clamav clamav-update

But still a older version of clamav which is 0.98.7 get's installed and gives me ClamAV Outdated warning in each freshclam. If I try to manually update clamav using yum update clamav it says it is in the latest version. Maybe the epel repo needs to be updated for the latest version of clamav which is 0.99

ClamAV admins please upgrade that repo as soon as possible because I am building my new web hosting server and needs to provide the most latest version of ClamAV and ClamAV Databases for better user security.


Thanks in advance...

**Comment by smfreegard** [comment]
EPEL has nothing to do with the ClamAV developers... it's run by Fedora. https://fedoraproject.org/wiki/EPEL#Communicating_with_the_EPEL_SIG

If you don't like it - either build from source or learn how to build RPMs for yourself.

**Comment by uGiFarukh** [comment]
How can I build ClamAV from source which will be totally compatible to work properly with CentOS 6.7 Final? Can you please guide me through commands? Because the installing clamav from source guide in this git repo's wiki is not very much descriptive. If possible please guide me through command lines on how to properly install clamav 0.99 from its source and compatible with CentOS 6.7 Final.


Thanks in advance...

**Comment by uGiFarukh** [comment]
Contacted with EPEL and they will soon update their repo with the latest one...
