### ISSUE TITLE
(Feature request) Failover option for on-access scanning if CONFIG_FANOTIFY_ACCESS_PERMISSIONS is not enabled

### ISSUE THREAD

**Issue by nathanross** [vrtadmin/clamav-devel#17]
Debian does not enable fanotify-based blocking by default, and is unlikely to do that anytime soon out of performance concerns for the average user that doesn't make use of it (See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=690737).

It would be nice if there was a way for debian users to have read-blocking scanning without having to compile a kernel with this option; though I recognize there aren't many elegant options available to do this. 

For many security environments having on-access scanning is important, but not as important as having a commercially supported kernel configuration. A failover option would allow debian servers to have both.

An example use case where read-blocking would apply. (debian jessie):

1. apt-get install clamav-daemon
2. mkdir /mnt/example /mnt/quarantine
3. Set clamd.conf options:
    * OnAccessIncludePath /mnt/example
    * VirusEvent mv $CLAM_VIRUSEVENT_FILENAME /mnt/quarantine
    * ScanOnAccess true
4. cd /mnt/example && wget https://secure.eicar.org/eicar.com.txt
5. systemctl restart clamav-daemon
6. cat eicar.com.txt

Notice that the file will be moved, but only after getting the contents of the file.

**Comment by vrtadmin** [comment]
Our official bug tracker is at https://bugzilla.clamav.net

Please file your bug there.

For any discussions on the issue, please see the ClamAV-Users or ClamAV-Devel mailing lists here:

http://www.clamav.net/contact#ml
