### ISSUE TITLE
Virus Report

### ISSUE THREAD

**Issue by pavlinux** [vrtadmin/clamav-devel#19]
https://www.virustotal.com/ru/file/77a2097cb6ca81604a67c9706a32a5e9eac0318753cb0ea5e9a2aba62b69d245/analysis/1427446740/

Virus http://filebin.ca/1wFcQ34teLwl/5604189256balanc.zip

**Comment by vrtadmin** [comment]
Please submit malware here:

http://www.clamav.net/contact#reports
