### ISSUE TITLE
freshclam 0.98.7 database load killed by signal 11

### ISSUE THREAD

**Issue by nijikon** [vrtadmin/clamav-devel#23]
```
balrog:~ n$ freshclam
ClamAV update process started at Sun Jun 28 22:22:17 2015
main.cvd is up to date (version: 55, sigs: 2424225, f-level: 60, builder: neo)
daily.cvd is up to date (version: 20616, sigs: 1443371, f-level: 63, builder: shurley)
Downloading bytecode.cvd [100%]
ERROR: Database load killed by signal 11
ERROR: Failed to load new database
balrog:~ n$ freshclam --version
ClamAV 0.98.7/20616/Sun Jun 28 06:19:41 2015
balrog:~ n$ brew --config
HOMEBREW_VERSION: 0.9.5
ORIGIN: git@github.com:polishgeeks/homebrew.git
HEAD: 376c055d7463f61d144fa0f0484d2611a4c80d96
Last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit haswell
OS X: 10.10.4-x86_64
Xcode: 6.3.2
CLT: 6.3.2.0.1.1431401888
Clang: 6.1 build 602
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/n/.rvm/rubies/ruby-2.2.2/bin/ruby
Java: 1.8.0_45
```

**Comment by graemeglass** [comment]
Seeing the same issue: 

->freshclam
ClamAV update process started at Fri Jul 10 14:31:07 2015
main.cvd is up to date (version: 55, sigs: 2424225, f-level: 60, builder: neo)
Downloading daily-20630.cdiff [100%]
...
daily.cld updated (version: 20671, sigs: 1470869, f-level: 63, builder: neo)
Downloading bytecode.cvd [100%]
ERROR: Database load killed by signal 11
ERROR: Failed to load new database

->freshclam --version
ClamAV 0.98.7/20671/Fri Jul 10 10:56:39 2015

->  brew --config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: 4056cf4caf85d71968e7a87259bc5585d620432b
Last commit: 10 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit ivybridge
OS X: 10.10.4-x86_64
Xcode: 6.4
CLT: 6.4.0.0.1.1435007323
Clang: 6.1 build 602
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: 1.6.0_65

**Comment by wfiveash** [comment]
I'm seeing the same problem.  For now "brew switch clamav 0.98.6" fixed this issue.

**Comment by bingh0** [comment]
Hi, I noticed that this bug has been filed upstream with a workaround.
https://bugzilla.clamav.net/show_bug.cgi?id=11309

Also seems that the developers recommend workaround (compile with --enable-llvm=no) and using latest version 0.98.7 rather than older version.
