### ISSUE TITLE
clamav-0.99.1 configuration error

### ISSUE THREAD

**Issue by hdatma** [vrtadmin/clamav-devel#26]
Suppose you have a 64bit-only architecture, your compiler is llvm/clang, 
and you want to install clamav on a path of your own. 

The following triggers an error:

> ./configure --prefix=/my/path <...>

clang: error: unsupported option '-print-multi-os-directory'
clang: error: no input files

There is a problem with clamav's configurator, because we do not need 
the result of "gcc -print-multi-os-directory". In fact, we set the default
libdir implicitly, when setting the custom prefix, but the configurator 
ignored the custom value. 

* Ref. ChangeLog: 

Mon Oct 20 17:23:12 EEST 2008 (edwin)
-------------------------------------
 * aclocal.m4, configure, configure.in, m4/acinclude.m4,
 m4/lib-prefix.m4: use -print-multi-os-directory to set default
 libdir (bb #1240) 
 * WARNING: On a 64-bit multiarch OS, this will by
 default install libclamav into /usr/local/lib64, if your system uses
 /usr/local/lib for 32bit apps.  If the system uses /usr/local/lib
 for 64-bit apps and lib32 for 32bit apps, there is no change (unless
 you use -m32).

* Ref. configure  --help 

--prefix=PREFIX         install architecture-independent files in PREFIX [/usr/local]
--exec-prefix=EPREFIX   install architecture-dependent files in EPREFIX [PREFIX]
--libdir=DIR            object code libraries [EPREFIX/lib]

To solve the problem from the command line, it is sufficient to specify libdir again:

> ./configure --prefix=/my/path --libdir=/my/path/lib <...>

**Comment by vrtadmin** [comment]
A more appropriate place to get your question answered would be the ClamAV users list:

http://lists.clamav.net/mailman/listinfo/clamav-users
