### ISSUE TITLE
clamd's SHUTDOWN command is unreasonable

### ISSUE THREAD

**Issue by surrim** [vrtadmin/clamav-devel#28]
The SHUTDOWN command should be disabled by default. At the moment you cannot run clamd in a production environment. Anybody can kill the process from outside to prevent it from doing its job. Using a proxy to block SHUTDOWN commands or installing clamd on every server instance is complicated or rather no option. At least there should be a way to disable this command, maybe in the configuration file.

**Comment by Varbin** [comment]
I tried to write a patch for this problem (but I have not tested it yet):

```diff
--- clamav-0.99.2-orig/clamd/session.c    2016-04-22 17:02:18.000000000 +0200
+++ clamav-0.99.2/clamd/session.c    2016-06-23 14:28:02.248451000 +0200
@@ -562,11 +562,15 @@
     }
 
     switch (cmd) {
+        /********************************************
+        * Disable shutdown over socket *
+
     case COMMAND_SHUTDOWN:
         pthread_mutex_lock(&exit_mutex);
         progexit = 1;
         pthread_mutex_unlock(&exit_mutex);
         return 1;
+    *********************************************/
     case COMMAND_RELOAD:
         pthread_mutex_lock(&reload_mutex);
         reload = 1;
```

**Comment by surrim** [comment]
Thanks for the patch. I located the lines also, but I thought it would be better to start a discussion about this dubious "feature". 9 months passed and nothing happened. It is still not usable for production environments.

**Comment by Varbin** [comment]
I think the official site for reporting bugs is: https://bugzilla.clamav.net. I believe issues on GitHub are just ignored.

**Comment by vrtadmin** [comment]
They aren't ignored.  We just don't check it as often.  But yes @Varbin is correct.  The place for bugs is Bugzilla.clamav.net.  Please file a bug there.
