### ISSUE TITLE
os_generic is not defined

### ISSUE THREAD

**Issue by photoszzt** [vrtadmin/clamav-devel#32]
Try to cross compile clamav-0.98.7, get the following error:
libclamav/bytecode_detect.c:242: error: 'os_generic' undeclared (first use in this function)

I do not find the enum defined in enum os_kind_conf. The only close meaning enum I find is os_unknown. Should it be os_unknown rather than os_generic?

**Comment by vrtadmin** [comment]
A more appropriate place to get your question answered would be the ClamAV devel list:

http://lists.clamav.net/mailman/listinfo/clamav-devel
