### ISSUE TITLE
Bug on file JITDebugRegister file. it's take effect to LLVMjit cannot build sub project success. In ClamAV version 0.98.1

### ISSUE THREAD

**Issue by rchatsiri** [vrtadmin/clamav-devel#4]
Cross post at the clamav-devel mail-list. I'm was forked source code in the master branch at version 0.98.1.

Hello All, 

   I found incorrect code on the sub-project LLVMjit. It cannot built a source code success because using std::make_pair<std::string, jit_code_entry*>(Buffer, JITCodeEntry);   in line 146. Follow line of code as file name is JITDebugRegister.cpp.

 ```FnMap[F] = std::make_pair<std::string, jit_code_entry*>(Buffer, JITCodeEntry);```

It should be example code below.

 ```FnMap[F] = std::pair<std::string, jit_code_entry*>(Buffer, JITCodeEntry);```

In declaration variable  FnMap[F] is type definition declares as below in the file name JITDebugRegister.h

```typedef DenseMap< const Function*, std::pair<std::string, jit_code_entry*> >
  RegisteredFunctionsMap;```

FnMap[F] must lvalue received the value std::pair<std::string, jit_code_entry*>(Buffer, JITCodeEntry); more std::map<T,T2>().Thus,source code use std::pair<T,T2>() instead std::make_pair(). Program will compiler source code success.

Example fixed bug in line 14 from my gits: https://gist.github.com/Chatsiri/11295674

Project build source code in Microsoft Visual Studio 2013 (Version 12.0.21005.1 REL), Windows 7 
Repository : https://github.com/vrtadmin/clamav-devel 

Best Regards,
R.Chatsiri.

**Comment by vrtadmin** [comment]
Our official bug tracker is at https://bugzilla.clamav.net

Please file your bug there.

For any discussions on the issue, please see the ClamAV-Users or ClamAV-Devel mailing lists here:

http://www.clamav.net/contact#ml
