### ISSUE TITLE
Scanning files bigger then 4GB

### ISSUE THREAD

**Issue by mbn18** [vrtadmin/clamav-devel#45]
I wish to scan files that are bigger then 4GB. For example video files.

I noticed clamav is limited (code based on 32bit?). So, is there a workaround or maybe this feature is under development?

**Comment by ROCKNROLLKID** [comment]
I am almost positive that ClamAV does have 64-bit builds, but I don't see much point in scanning such large files. ClamAV is meant to be a mail scanner and, as far as I know, no mail server can even send a file that's larger then 4GB. I don't think I have ever seen one be able to send one that is over 1GB.

**Comment by lattera** [comment]
ClamAV doesn't support scanning files larger than 2.7GB due to constraints in the scanning engine.

**Comment by ROCKNROLLKID** [comment]
Thank you Shawn. I do not see much point in scanning files larger then that considering most mail servers are limited to 50-100mb size, but I guess there are always those paranoid users out there. Who knows, maybe one day it will happen.
