### ISSUE TITLE
Error: cl_load(): No such file or directory

### ISSUE THREAD

**Issue by frankstein-1** [vrtadmin/clamav-devel#46]
Hello 

I installed clamav as mentioned in the section 3.2 Installing on shell account, using the following commands 
```bash
 ./configure --prefix=/home/user/programming/clamav --disable-clamav
 make 
 make install 
```
As you see it doesn't work for me. 
```bash
./clamscan ~
LibClamAV Error: cl_load(): No such file or directory: /home/user/programming/clamav/share/clamav
ERROR: Can't get file status

----------- SCAN SUMMARY -----------
Known viruses: 0
Engine version: devel-20151207
Scanned directories: 0
Scanned files: 0
Infected files: 0
Data scanned: 0.00 MB
Data read: 0.00 MB (ratio 0.00:1)
Time: 0.011 sec (0 m 0 s)
```

**Comment by kevlin2** [comment]
Make sure to pull the most up-to-date databases with the 'freshclam' program. For additional questions on the general usage of ClamAV programs, please refer to the 'clamdoc.pdf' document in the 'docs' directory of the ClamAV source distribution (https://github.com/vrtadmin/clamav-devel/blob/master/docs/clamdoc.pdf).
