### ISSUE TITLE
OnAccess recursive prevention

### ISSUE THREAD

**Issue by berdario** [vrtadmin/clamav-devel#49]
Is this thing actually possible with any ClamAV version?

This is my understanding of the current situation:

The only way to have recursive OnAccess is with `OnAccessMountPath`, which plays together with DDD

versions of ClamAV before 0.99 don't have DDD. Using `OnAccessIncludePath` also requires `OnAccessDisableDDD`, and will only keep track of the immediate directory specified by `OnAccessIncludePath`.

Due to [this commit](https://github.com/vrtadmin/clamav-devel/commit/f408e5b2cec2e203f24b520aa5e1fd97a186249a), adding the following code

```
if (!optget(tharg->opts, "OnAccessNotifyOnly")->enabled && !optget(tharg->opts, "OnAccessMountPath")->enabled) {
	    logg("ScanOnAccess: preventing access attempts on malicious files.\n");
	    fan_mask |= FAN_ACCESS_PERM | FAN_OPEN_PERM;
     } else {
	    logg("ScanOnAccess: notifying only for access attempts.\n");
```

the `!optget(tharg->opts, "OnAccessMountPath")->enabled)` will disable access prevention when `OnAccessMountPath` is configured. Conversely access prevention works with `OnAccessIncludePath`+`OnAccessDisableDDD`, but this will only have non-recursive OnAccess protection.

**Comment by berdario** [comment]
By looking [here](https://github.com/vrtadmin/clamav-devel/blob/ea9ffd2/etc/clamd.conf.sample#L581) I realized that it's actually sort of documented:

>  This will notify only.

Still, the [commit I linked before](https://github.com/vrtadmin/clamav-devel/commit/f408e5b2cec2e203f24b520aa5e1fd97a186249a) doesn't explain why this has been disabled. Is it due to performance issues?

Even if that was the reason, Clam should respect what the user explicitly stated in the configuration

**Comment by vrtadmin** [comment]
Our official bug tracker is at https://bugzilla.clamav.net

Please file your bug there.
