### ISSUE TITLE
Detect Different Files

### ISSUE THREAD

**Issue by KiarashS** [vrtadmin/clamav-devel#54]
Dear,

What is supported file types in clamav?
How i can detect Encrypted files?
How i can detect Password-Protected files?
How i can detect Destroyed files?
How i can detect Binded files?

Thanks

**Comment by vrtadmin** [comment]
A more appropriate place to get your question answered would be the ClamAV users list:

http://lists.clamav.net/mailman/listinfo/clamav-users

While I try, I can't get to everyone's email personally and this allows us to leverage everyone on the team as well as the whole open source community.

Thank you.
