### ISSUE TITLE
How add CL_SCAN_FILE_PROPERTIES option to clamdscan

### ISSUE THREAD

**Issue by ulyktey** [vrtadmin/clamav-devel#58]
Hello,

Could you please help me to add "CL_SCAN_FILE_PROPERTIES" option to clamdscan?

I want to detect macros into files. I have just opportunity to use clamdscan in my project. I have found the next page http://blog.clamav.net/2014/11/intro-to-collection-and-analysis-of.html. In this page, author has described how to use clamscan for detecting file properties. I have tried to add it to clamdscan but it did not work.

Thanks,
Yurii

**Comment by vrtadmin** [comment]
A more appropriate place to get your question answered would be the ClamAV users list:

http://lists.clamav.net/mailman/listinfo/clamav-users

While I try, I can't get to everyone's email personally and this allows us to leverage everyone on the team as well as the whole open source community.

Thank you.
