### ISSUE TITLE
cli_dconf_load() treats "MACHO:" as 4 bytes in two lines of code

### ISSUE THREAD

**Issue by marktayl** [vrtadmin/clamav-devel#9]
I noticed this during inspection:

In 0.98.4, I see that libclamav/dconf.c:cli_dconf_load() does this comparison:

        if(!strncmp(buffer, "MACHO:", 4) && chkflevel(buffer, 2)) {
            if(sscanf(buffer + 4, "0x%x", &val) == 1) {

I believe that the author mean ("MACHO:", 5) in the strncmp(), and "buffer + 5" in the sscanf().

**Comment by steve-morgan** [comment]
This will go in 0.99.1:

        if(!strncmp(buffer, "MACHO:", 6) && chkflevel(buffer, 2)) {
            if(sscanf(buffer + 6, "0x%x", &val) == 1) {
It is 6 to account for the ':'.
